version: "3.9"

services:
  mariadb:
    container_name: mariadb-container
    image: mariadb:10.7.1-focal
    restart: unless-stopped
    volumes:
      - ./workdir/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - ./.env

  redis:
    container_name: redis-container
    image: redis:7.0-rc-bullseye
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: unless-stopped
    volumes:
      - ./workdir/redis:/usr/local/etc/redis
    ports:
      - 6379:6379
    env_file:
      - ./.env

  mongo:
    container_name: mongo-container
    image: mongo:focal
    restart: unless-stopped
    volumes:
      - ./workdir/mongo:/etc/mongo
    ports:
      - "27017:27017"
    env_file:
      - ./.env

  postgres:
    container_name: postgres-container
    image: postgres:bullseye
    restart: unless-stopped
    volumes:
      - ./workdir/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
