version: "3.9"

services:
  # SDKs Services
  dotnet:
    container_name: dotnet-container
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    restart: unless-stopped
    volumes:
      - ./workdir:/app/workdir
    #env_file:
    # - ./workdir/path/to/env_file
    #ports:
    # - 8080:8080
