version: "3.9"

networks:
  # Make isolated networks
  isolated:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
  # Make outsider networks
  outsider:
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/16"

services:
  # SDKs Services
  sdks:
    container_name: net-sdks-container
    build: .
    restart: unless-stopped
    volumes:
      - ~/kontainer-devenv/dotnet/workdir:/app/workdir
    networks:
      isolated:
        #ipv4_address: 172.20.0.1
        aliases:
          - sdks.isolated
      outsider:
        #ipv4_address: 172.22.0.1
        aliases:
          - sdks.outsider
    #env_file:
    # - ./workdir/path/to/env_file
    #ports: 8080:8080
