version: "3.9"

services:
  # SDKs Services
  dotnet:
    container_name: dotnet-container
    build:
      context: .
      args:
        UID: ${DOTNET_UID_CONTAINER}
        GID: ${DOTNET_GID_CONTAINER}
        DOTNET_TOOLS: ${DOTNET_TOOLS}
    restart: unless-stopped
    volumes:
      - ./workdir:/app/workdir
    env_file:
     - ./.env
